import { useLayoutEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { COVER_PILLARS } from '../lib/pillars'
import { COVER_PILLAR_HEIGHT } from '../lib/constants'
import { useGameStore } from '../store/gameStore'
import { getLevel } from '../lib/levels'

const ACCENT_BAND_HEIGHT = 0.4

/** Renders the scattered cover pillars as containment-crate columns — one
 * InstancedMesh draw call for the shafts and one more for the metallic
 * accent band, instead of a mesh per obstacle. Positions come straight
 * from COVER_PILLARS (lib/pillars.ts), the same array the line-of-sight
 * "acoustic shadow" check reads, so rendering and collision can never
 * disagree about where a pillar actually is. The shafts stay cylindrical
 * (matching the circle-based collision math exactly) rather than boxy
 * crates, so there's no gap between what you see and what actually blocks
 * a shout.
 *
 * Experience.tsx mounts this with `key={levelIndex}`, so advancing a floor
 * fully unmounts the old InstancedMeshes (disposing their GPU buffers the
 * normal React/Three.js way) and mounts fresh ones sized for the new
 * floor's pillar count — COVER_PILLARS itself was already regenerated by
 * the store action that changed levelIndex, before this remount happens. */
export function CoverPillars() {
  const shaftRef = useRef<THREE.InstancedMesh>(null)
  const bandRef = useRef<THREE.InstancedMesh>(null)
  const levelIndex = useGameStore((s) => s.levelIndex)
  const level = useMemo(() => getLevel(levelIndex), [levelIndex])
  const accentBandRadius = level.pillarRadius * 1.04
  const accentBandY = COVER_PILLAR_HEIGHT * 0.72

  useLayoutEffect(() => {
    const shaft = shaftRef.current
    const band = bandRef.current
    if (!shaft || !band) return
    const dummy = new THREE.Object3D()

    COVER_PILLARS.forEach((pillar, i) => {
      dummy.position.set(pillar.x, COVER_PILLAR_HEIGHT / 2, pillar.z)
      dummy.updateMatrix()
      shaft.setMatrixAt(i, dummy.matrix)

      dummy.position.set(pillar.x, accentBandY, pillar.z)
      dummy.updateMatrix()
      band.setMatrixAt(i, dummy.matrix)
    })
    shaft.instanceMatrix.needsUpdate = true
    band.instanceMatrix.needsUpdate = true
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [levelIndex])

  if (COVER_PILLARS.length === 0) return null

  return (
    <>
      <instancedMesh ref={shaftRef} args={[undefined, undefined, COVER_PILLARS.length]} castShadow receiveShadow>
        <cylinderGeometry args={[level.pillarRadius, level.pillarRadius, COVER_PILLAR_HEIGHT, 12]} />
        <meshStandardMaterial color={level.crateColor} roughness={0.4} metalness={0.3} />
      </instancedMesh>
      <instancedMesh ref={bandRef} args={[undefined, undefined, COVER_PILLARS.length]}>
        <cylinderGeometry args={[accentBandRadius, accentBandRadius, ACCENT_BAND_HEIGHT, 12]} />
        <meshStandardMaterial color={level.crateAccentColor} roughness={0.25} metalness={0.7} />
      </instancedMesh>
    </>
  )
}
