import { useLayoutEffect, useRef } from 'react'
import * as THREE from 'three'
import { COVER_PILLARS, PET_STORE_ITEM_KINDS } from '../lib/pillars'
import { COVER_PILLAR_HEIGHT } from '../lib/constants'

const ACCENT_BAND_HEIGHT = 0.4
const ACCENT_BAND_RADIUS_FACTOR = 1.04
const ACCENT_BAND_Y = COVER_PILLAR_HEIGHT * 0.72

function accentColorFor(color: string): string {
  return PET_STORE_ITEM_KINDS.find((k) => k.color === color)?.accentColor ?? color
}

/** Renders the scattered pet-store obstacles — fish tanks, food bags,
 * scratching posts — as one InstancedMesh draw call for the shafts and one
 * more for the accent bands, instead of a mesh per obstacle. Both share a
 * single unit-radius cylinder geometry; every instance supplies its own
 * footprint (non-uniform XZ scale) and EXACT solid color (instanceColor),
 * so one draw call still renders every distinct item size and hue.
 * Positions/radii/colors come straight from COVER_PILLARS (lib/pillars.ts),
 * the same array the color-match survival check and the Bot's hiding AI
 * read, so rendering and gameplay can never disagree about where an item
 * is or what color it is. The shafts stay cylindrical (matching the
 * circle-based collision math exactly) rather than boxy crates, so there's
 * no gap between what you see and what actually blocks a shout / can be
 * camouflaged against.
 *
 * Experience.tsx mounts this with `key={levelIndex}`, so advancing a floor
 * fully unmounts the old InstancedMeshes (disposing their GPU buffers the
 * normal React/Three.js way) and mounts fresh ones sized for the new
 * floor's item count — COVER_PILLARS itself was already regenerated by
 * the store action that changed levelIndex, before this remount happens. */
export function CoverPillars() {
  const shaftRef = useRef<THREE.InstancedMesh>(null)
  const bandRef = useRef<THREE.InstancedMesh>(null)

  useLayoutEffect(() => {
    const shaft = shaftRef.current
    const band = bandRef.current
    if (!shaft || !band) return
    const dummy = new THREE.Object3D()

    COVER_PILLARS.forEach((pillar, i) => {
      dummy.position.set(pillar.x, COVER_PILLAR_HEIGHT / 2, pillar.z)
      dummy.scale.set(pillar.radius, 1, pillar.radius)
      dummy.updateMatrix()
      shaft.setMatrixAt(i, dummy.matrix)
      shaft.setColorAt(i, new THREE.Color(pillar.color))

      const accentRadius = pillar.radius * ACCENT_BAND_RADIUS_FACTOR
      dummy.position.set(pillar.x, ACCENT_BAND_Y, pillar.z)
      dummy.scale.set(accentRadius, 1, accentRadius)
      dummy.updateMatrix()
      band.setMatrixAt(i, dummy.matrix)
      band.setColorAt(i, new THREE.Color(accentColorFor(pillar.color)))
    })
    shaft.instanceMatrix.needsUpdate = true
    if (shaft.instanceColor) shaft.instanceColor.needsUpdate = true
    band.instanceMatrix.needsUpdate = true
    if (band.instanceColor) band.instanceColor.needsUpdate = true
  }, [])

  if (COVER_PILLARS.length === 0) return null

  return (
    <>
      <instancedMesh ref={shaftRef} args={[undefined, undefined, COVER_PILLARS.length]} castShadow receiveShadow>
        <cylinderGeometry args={[1, 1, COVER_PILLAR_HEIGHT, 16]} />
        <meshStandardMaterial color="#ffffff" roughness={0.4} metalness={0.3} />
      </instancedMesh>
      <instancedMesh ref={bandRef} args={[undefined, undefined, COVER_PILLARS.length]}>
        <cylinderGeometry args={[1, 1, ACCENT_BAND_HEIGHT, 16]} />
        <meshStandardMaterial color="#ffffff" roughness={0.25} metalness={0.7} />
      </instancedMesh>
    </>
  )
}
